name: Fetch Data

on:
  # Run workflow automatically ever 2 days at 8:00 UTC
  schedule:
    - cron: "0 8 */2 * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions from commit changes
permissions:
  contents: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "fetch"
  cancel-in-progress: true

jobs:
  # Build job
  fetch:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # sets up .NET Core SDK 3.1
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3

    # checkout
    - uses: actions/checkout@v3

    # run the Scraper project on the Data folder
    - name: Run Scraper
      run: dotnet run --project src/Scraper/Scraper.csproj -c Release -- Data

    # commit changes
    - name: Commit changes
      run: |
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add Data
        if git diff-index --quiet HEAD --; then
          echo "::warning:: No changes to commit"
        else
          git commit -m "Update Data"
          git push
        fi
